# # Используем официальный образ Node.js как базовый
# FROM node:16 AS build

# # Устанавливаем рабочую директорию
# WORKDIR /app

# # Копируем package.json и package-lock.json
# COPY package*.json ./

# # Устанавливаем зависимости
# RUN npm install

# # Копируем все файлы проекта в контейнер
# COPY . .

# # Собираем проект
# RUN npm run build

# #Используем Nginx для раздачи статических файлов
# FROM nginx:alpine

# # Копируем собранные файлы из предыдущего этапа
# COPY --from=build /app/build /usr/share/nginx/html

# # Открываем порт 80
# EXPOSE 3000

# #Запускаем Nginx
# CMD ["nginx", "-g", "daemon off;"]
# # RUN npm start

# устанавливаем официальный образ Node.js
FROM node:19-alpine

# указываем рабочую (корневую) директорию
WORKDIR /app

# копируем основные файлы приложения в рабочую директорию
COPY package.json package-lock.json ./

# устанавливаем указанные зависимости NPM на этапе установки образа
RUN npm install

# после установки копируем все файлы проекта в корневую директорию
COPY . ./

# запускаем основной скрипт в момент запуска контейнера
CMD npm start