version: '3.8'

services:

  db:
    restart: always
    image: postgres:11.11
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - ./db/:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biji

  frontend:
      build:
        context: ./front-quiz     # Путь к папке, где находится Dockerfile
        dockerfile: dockerfile     # Имя Dockerfile (по умолчанию)
      ports:
        - 3000:3000                 # Пробрасываем порт
      networks:
        - frontend-network         # Сеть, которую мы создадим ниже

networks:
  frontend-network:
    driver: bridge              # Используем мостовую сеть