version: '3.8'

services:

  db:
    restart: always
    image: postgres:11.11
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - ./db/:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=iot
      - POSTGRES_PASSWORD=samsung
      - POSTGRES_DB=biji

  frontend:
      build:
        context: ./front-quiz     # Путь к папке, где находится Dockerfile
        dockerfile: Dockerfile     # Имя Dockerfile (по умолчанию)
      ports:
        - 3000:3000                 # Пробрасываем порт

  web:
    build: .
#    image: shureck/forcicd:latest
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    depends_on:
      - db